name: Docker Build and Secure Push

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME_FRONT: frontend-security
  IMAGE_NAME_BACK: backend
  IMAGE_TAG: latest

jobs:
  build-scan-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Frontend Docker Image
        run: |
          docker build -t $IMAGE_NAME_FRONT:$IMAGE_TAG -f mern/frontend/Dockerfile .

      # Optional: Uncomment to enable Trivy scanning
      # - name: Scan Image with Trivy
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: $IMAGE_NAME_FRONT:$IMAGE_TAG
      #     format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true

      - name: Push Docker Image to DockerHub
        run: |
          docker tag $IMAGE_NAME_FRONT:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME_FRONT:$IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME_FRONT:$IMAGE_TAG
